# Generated by Django 4.2.30 on 2026-06-22 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse_livraison", models.TextField()),
                ("ville", models.CharField(max_length=100)),
                ("code_postal", models.CharField(max_length=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("confirmee", "Confirmée"),
                            ("en_preparation", "En cours de préparation"),
                            ("expediee", "Expédiée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=30,
                    ),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "frais_livraison",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_produit", models.CharField(max_length=200)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="commandes.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.produit",
                    ),
                ),
            ],
        ),
    ]
