# Generated by Django 4.2.15 on 2026-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("carte", "Carte bancaire"),
                    ("cod", "Paiement à la livraison (COD)"),
                    ("virement", "Virement bancaire"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
