# Generated by Django 4.2.15 on 2026-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="icon",
            field=models.CharField(default="bi-grid", max_length=50),
        ),
    ]
