# Generated by Django 4.2.15 on 2026-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_categorie_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.TextField()),
                ("image", models.ImageField(upload_to="hero/")),
                ("button_text", models.CharField(max_length=50)),
                ("button_link", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
