# Generated by Django 4.2.15 on 2026-07-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_favori"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("logo", models.ImageField(upload_to="marques/")),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
    ]
